client:
  file-synchronization-enabled: true
  schedule-delay: PT30S
  local-folder: ${CDR_CLIENT_LOCAL_FOLDER:${HOME}/Documents/cdr/inflight}
  idp-credentials:
    tenant-id: ${CDR_B2C_TENANT_ID:test-tenant-client-id} # `test-tenant-client-id` is the required value if the MockOauth2Server is used; see its `config.json`
    client-id: ${CDR_CLIENT_ID:easy-system-test-user-id}
    scopes:
      - https://dev.identity.health.swisscom.ch/CdrApi/.default
    client-secret: ${CDR_CLIENT_SECRET:Placeholder_test-secret}
    renew-credential: true
    last-credential-renewal-time: 2030-01-01T00:00:00Z
  file-busy-test-strategy: file_size_changed # valid values are `never_busy`, `file_size_changed`, `always_busy`
  cdr-api:
    scheme: http
    port: 9090
    host: localhost
    base-path: documents
  credential-api:
    scheme: ${client.cdr-api.scheme}
    port: ${client.cdr-api.port}
    host: ${client.cdr-api.host}
    base-path: client-credentials
  retry-template:
    retries: 1
  customer:
    - connector-id: 1
      target-folder: ${CDR_CLIENT_TARGET_FOLDER:${HOME}/Documents/cdr/target}/${client.customer[0].connector-id}/test
      source-folder: ${CDR_CLIENT_SOURCE_FOLDER:${HOME}/Documents/cdr/source}/${client.customer[0].connector-id}/test
      content-type: application/forumdatenaustausch+xml;charset=UTF-8
      source-archive-enabled: false
      source-archive-folder: ${java.io.tmpdir}
      source-error-folder: errors
      mode: test
      doc-type-folders:
        invoice:
          target-folder: ${CDR_CLIENT_TARGET_FOLDER:${HOME}/Documents/cdr/target}/${client.customer[0].connector-id}/test/invoice
          source-folder: ${CDR_CLIENT_SOURCE_FOLDER:${HOME}/Documents/cdr/source}/${client.customer[0].connector-id}/test/invoice
        credit:
          source-folder: ${CDR_CLIENT_TARGET_FOLDER:${HOME}/Documents/cdr/source}/${client.customer[0].connector-id}/test/credit
    - connector-id: 1
      target-folder: ${CDR_CLIENT_TARGET_FOLDER:${HOME}/Documents/cdr/target}/${client.customer[1].connector-id}
      source-folder: ${CDR_CLIENT_SOURCE_FOLDER:${HOME}/Documents/cdr/source}/${client.customer[1].connector-id}
      content-type: application/forumdatenaustausch+xml;charset=UTF-8
      source-archive-enabled: false
      source-archive-folder: ${java.io.tmpdir}
      source-error-folder: errors
      mode: production
      doc-type-folders:
        invoice:
          target-folder: ${CDR_CLIENT_TARGET_FOLDER:${HOME}/Documents/cdr/target}/${client.customer[1].connector-id}
          source-folder: ${CDR_CLIENT_SOURCE_FOLDER:${HOME}/Documents/cdr/source}/${client.customer[1].connector-id}
        credit:
          source-folder: ${CDR_CLIENT_TARGET_FOLDER:${HOME}/Documents/cdr/source}/${client.customer[1].connector-id}
#    - connector-id: 1
#      content-type: application/forumdatenaustausch+xml;charset=UTF-8
#      target-folder: ${CDR_CLIENT_TARGET_FOLDER:${HOME}/Documents/cdr/target}/${client.customer[1].connector-id}
#      source-folder: ${CDR_CLIENT_SOURCE_FOLDER:${HOME}/Documents/cdr/source}/${client.customer[1].connector-id}
#      mode: production
#    - connector-id: 1234
#      content-type: application/forumdatenaustausch+xml;charset=UTF-8
#      target-folder: ${CDR_CLIENT_TARGET_FOLDER:${HOME}/Documents/cdr/target}/${client.customer[2].connector-id}
#      source-folder: ${CDR_CLIENT_SOURCE_FOLDER:${HOME}/Documents/cdr/source}/${client.customer[2].connector-id}
#      source-archive-enabled: true
#      source-archive-folder: archive
#      mode: test
#      doc-type-folders:
#        invoice:
#          source-folder: ${CDR_CLIENT_SOURCE_FOLDER:${HOME}/Documents/cdr/source}/${client.customer[2].connector-id}/invoice
#    - connector-id: 5
#      content-type: application/forumdatenaustausch+xml;charset=UTF-8
#      target-folder: ${CDR_CLIENT_TARGET_FOLDER:${HOME}/Documents/cdr/target}/${client.customer[3].connector-id}
#      source-folder: ${CDR_CLIENT_SOURCE_FOLDER:${HOME}/Documents/cdr/source}/${client.customer[3].connector-id}
#      mode: test
#    - connector-id: 666
#      content-type: application/forumdatenaustausch+xml;charset=UTF-8
#      target-folder: ${CDR_CLIENT_TARGET_FOLDER:${HOME}/Documents/cdr/target}/${client.customer[4].connector-id}
#      source-folder: ${CDR_CLIENT_SOURCE_FOLDER:${HOME}/Documents/cdr/source}/${client.customer[4].connector-id}
#      mode: production
#    - connector-id: 2345
#      content-type: application/forumdatenaustausch+xml;charset=UTF-8
#      target-folder: ${CDR_CLIENT_TARGET_FOLDER:${HOME}/Documents/cdr/target}/${client.customer[5].connector-id}
#      source-folder: ${CDR_CLIENT_SOURCE_FOLDER:${HOME}/Documents/cdr/source}/${client.customer[5].connector-id}
#      mode: production
